config/routes.rb
Labtool::Application.routes.draw do
  resources :peer_reviews
  resources :week_feedbacks
  resources :feedback_comments
  resources :registrations
  resources :checklists
  resources :checks
  resources :checktypes
  resources :courses
  resources :peer_reviews
  resources :users do
    post 'toggle_hidden', :on => :member
  end

  get  'checklists/:id/user/:registration_id' => 'passed_checks#show'
  post 'checklists/:id/user/' => 'passed_checks#update'
  get  'checklists/:id/values/' => 'checklists#edit_values', :as => "edit_checklist_values"
  get  'checklists/ajax/new_topic_form' => 'checklists#new_topic'
  get  'checklists/ajax/new_check_form' => 'checklists#new_check'
  get  'checklists/ajax/import_check_form' => 'checklists#import_check'
  post 'checklists/:id/values/' => 'checklists#update_values'

  post 'checktypes/:id/reorder/' => 'checks#reorder'

  match 'register(/:id)' => 'registrations#new'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  match 'courses/:id/active' => 'courses#active', :via => :post
  match 'courses/:id/inactive' => 'courses#inactive', :via => :post

  match 'week_feedbacks/note' => 'week_feedbacks#create_note', :via => :post
  match 'feedback_comments/admin_reply' => 'feedback_comments#create_admin_reply', :via => :post

  get  'mypage' => 'mypage#index'
  post 'mypage' => 'mypage#redirect'
  get  'mypage/:student_number' => 'mypage#show'
  post 'mypage/:student_number' => 'mypage#edit'
  match 'mypage/:student_number' => 'mypage#update',  :via => :put

  match 'foobar' => 'mypage#foobar'
  match 'toggle_review' => 'peer_reviews#toggle_review'
  match 'remove_review' => 'peer_reviews#remove_review'
  match 'complete_review' => 'peer_reviews#complete_review'
  match 'reset_reviews' => 'peer_reviews#reset'
  match 'generate_reviews' => 'peer_reviews#generate'
  match 'toggle_review_participation' => 'peer_reviews#toggle_participation'
  post '/peer_review' => 'peer_reviews#create'

  match 'toggle_registration' => 'registrations#toggle_activity'
  match 'toggle_demo_participation' => 'registrations#toggle_demo_participation'

  post 'users/:id/toggle_admin' => 'users#toggle_admin', :as => "user_toggle_admin"

  root :to => 'mypage#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :forename, :student_number, :surename, :password, :password_confirmation

  has_secure_password

  has_many :registrations, :dependent => :destroy

  has_many :courses, :through => :registrations

  validates :student_number,
            :format => { :with => /\A0\d{8}\z/,
            :message => "should start with 0 and be followed by 8 digits" }

  def self.registered_for course
    Registration.where( :course_id => course.id ).includes(:user, :week_feedbacks).map{ |r| r.user }.uniq
    #User.select { |s| s.registered_to self }.sort_by{ |s| s.surename.downcase }
    #course.registrations.map{ |r| r.user }.uniq
  end

  def to_s
    "#{forename} #{surename}"
  end

  def registration_for_course course
    registrations.where(course_id: course).first
  end

  def reviews_user_for_course_round course
    registration_for_course(course).review_targets_for(course.review_round).first.reviewed.user
  end

  def reviewer_for_course_round? course
    registration_for_course(course).review_targets_for(course.review_round).any?
  end

  def review_target_for_course_round? course
    registration_for_course(course).reviewers_for(course.review_round).any?
  end

  def has_registered?(course)
    courses.include? course
  end

  def review_eligibility_for_course_round? course
    r = registration_for_course course
    (not r.nil?) and
        r.active and
        r.participates_review(course.review_round)
  end

  def active_registrations
    registrations.joins(:course).where(active: true, courses: {active: true})
  end

  def registered_to course
    registrations.map(&:course).include? course
  end

  def registration_to course
    registrations.select{ |r| r.course==course  }.first
  end

  def week_feedbacks
    current_registration.week_feedbacks
  end

  def past_registrations
    registrations.joins(:course).where('registrations.active = ? OR courses.active = ?', false, false)
  end


  def assigned_to_review user
    return "cancel" if includes?( current_registration.review_targets_for(Course.active.review_round), user.current_registration)
    "review"
  end

  def reviewed user, course
    review_status = status( registration_to(course).review_targets, user.registration_to(course) )
    return "" if review_status == nil
    return "todo" if review_status==false
    "DONE"
  end

  ## below perhaps not needed?

  def reviewed_in_round user, course, round
    review_status = status_in_round( registration_to(course).review_targets, user.registration_to(course), round )
    return "" if review_status == nil
    return "X"
    return "todo" if review_status==false
    "DONE"
  end

  def status review_targets, searched
    review_targets.each { |r|
      return r.done if r.reviewed == searched
    }
    nil
  end

  def status_in_round review_targets, searched, round
    review_targets.each { |r|
      return r.done if r.reviewed == searched and r.round == round
    }
    nil
  end

  def includes? review_targets, searched
    review_targets.each { |r|
      return true if r.reviewed == searched
    }

    false
  end

  def assigned_reviews_in course
    registration_for_course(course).review_targets_for course.review_round
  end

  def assigned_reviewers_in course
    registration_for_course(course).reviewers_for course.review_round
  end

  def assigned_reviews course
    registration_for_course(course).review_targets_for course.review_round
  end

  def assigned_reviewers course
    registration_for_course(course).reviewers_for course.review_round
  end

  def self.find_or_create params
    user = User.find_by_student_number params['student_number']
    return user unless user.nil?

    params['password'] = params['student_number']
    params['password_confirmation'] = params['student_number']
    User.create params
  end

  def self.review_participants course
    User.select do |s|
          s.registration_for_course course and
          s.registration_for_course(course).participates_review(course.review_round)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.order('surename', 'forename')
  end

  def show
    @user = User.find(params[:id])
    @checklists = Checklist.order :title
  end

  def toggle_hidden
    @user = User.find(params[:id])
    @user.hidden = (not @user.hidden?)
    @user.save
    redirect_to @user, notice: 'User was successfully updated.'
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def toggle_admin
    user = User.find(params[:id])
    user.admin = !user.admin
    user.save
    redirect_to users_path, notice: 'Admin status updated successfully'

  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      redirect_to @user, notice: 'Something wrong....'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user]) if current_user==@user
    redirect_to @user, notice: 'User was successfully updated.'
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was deleted.'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def review_point_label points
    return "give points" if points.nil?
    "update points"
  end

  def isHidden u
    return "hidden" if u.hidden?
    ""
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      Forename
      <br/>
      <%= f.text_field :forename %>
    </div>

    <div class="field">
      Surename
      <br/>
      <%= f.text_field :surename %>
    </div>

    <% if @user.new_record? %>

      <div class="field">
        Student_number
        <br/>
        <%= f.text_field :student_number %>
      </div>

    <% end %>

    <div class="field">
      Email
      <br/>
      <%= f.text_field :email %>
    </div>

    <% unless @user.new_record? %>
        You can leave the next fields empty if you do not change the password <br />
    <% end %>

    <div class="field">
      <% if @user.new_record? %>
        Password <br />
      <% else %>
        New password <br />
      <% end %>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      Password confirmation <br />
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Surename</th>
    <th>Forename</th>
    <th>Student number</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.surename %></td>
    <td><%= user.forename %></td>
    <td><%= user.student_number %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to user.admin ? 'Unadmin' : 'Admin', user_toggle_admin_path(user), method: :post, data: { confirm: "Are you sure you want to toggle admin status?" } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create new user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>