config/routes.rb
Labtool::Application.routes.draw do
  resources :peer_reviews
  resources :week_feedbacks
  resources :feedback_comments
  resources :registrations
  resources :checklists
  resources :checks
  resources :checktypes
  resources :courses
  resources :peer_reviews
  resources :users do
    post 'toggle_hidden', :on => :member
  end

  get  'checklists/:id/user/:registration_id' => 'passed_checks#show'
  post 'checklists/:id/user/' => 'passed_checks#update'
  get  'checklists/:id/values/' => 'checklists#edit_values', :as => "edit_checklist_values"
  get  'checklists/ajax/new_topic_form' => 'checklists#new_topic'
  get  'checklists/ajax/new_check_form' => 'checklists#new_check'
  get  'checklists/ajax/import_check_form' => 'checklists#import_check'
  post 'checklists/:id/values/' => 'checklists#update_values'

  post 'checktypes/:id/reorder/' => 'checks#reorder'

  match 'register(/:id)' => 'registrations#new'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  match 'courses/:id/active' => 'courses#active', :via => :post
  match 'courses/:id/inactive' => 'courses#inactive', :via => :post

  match 'week_feedbacks/note' => 'week_feedbacks#create_note', :via => :post
  match 'feedback_comments/admin_reply' => 'feedback_comments#create_admin_reply', :via => :post

  get  'mypage' => 'mypage#index'
  post 'mypage' => 'mypage#redirect'
  get  'mypage/:student_number' => 'mypage#show'
  post 'mypage/:student_number' => 'mypage#edit'
  match 'mypage/:student_number' => 'mypage#update',  :via => :put

  match 'foobar' => 'mypage#foobar'
  match 'toggle_review' => 'peer_reviews#toggle_review'
  match 'remove_review' => 'peer_reviews#remove_review'
  match 'complete_review' => 'peer_reviews#complete_review'
  match 'reset_reviews' => 'peer_reviews#reset'
  match 'generate_reviews' => 'peer_reviews#generate'
  match 'toggle_review_participation' => 'peer_reviews#toggle_participation'
  post '/peer_review' => 'peer_reviews#create'

  match 'toggle_registration' => 'registrations#toggle_activity'
  match 'toggle_demo_participation' => 'registrations#toggle_demo_participation'

  post 'users/:id/toggle_admin' => 'users#toggle_admin', :as => "user_toggle_admin"

  root :to => 'mypage#index'
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  attr_accessible :title, :ordering, :init_callback, :grade_callback, :remarks
  has_many :topics, class_name: 'ChecklistTopic', dependent: :destroy, autosave: true
  has_many :topics_checks,    through: :topics
  has_many :checks,    through: :topics_checks
  has_many :passed_checks, through: :checks
  has_many :scoretypes, through: :topics, :uniq => true, :order => 'name'
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

  def index
    @checklists = Checklist.order :title
  end

  def new
    @checklist = Checklist.new
    @listdata = topics_to_yaml(@checklist.topics.order "ordering")
  end
  
  def edit
    @checklist = Checklist.find(params[:id])
    @listdata = topics_to_yaml(@checklist.topics.order "ordering")
  end
    
  def show
    @checklist = Checklist.find(params[:id])
    @registration = nil
    @attribute_suffix = ""
    render :layout => !request.xhr?
  end

  def create
    begin
      @checklist = Checklist.new params[:checklist]
      @checklist.save
      
      redirect_to edit_checklist_values_path(@checklist), :notice => 'Checklist was successfully created.'
    rescue Exception => msg  
      
      @checklist = Checklist.new params[:checklist]
      @checklist.errors.add(:topics,msg)

      render :action => "new"
    end
  end

  def update
    @checklist = Checklist.find params[:checklist][:id]
    @checklist.title = params[:checklist][:title]
    @checklist.grade_callback = params[:checklist][:grade_callback]
    @checklist.remarks = params[:checklist][:remarks]
    begin
      old_checks = @checklist.checks
      @checklist.topics = yaml_to_topics(params[:topics_yaml])
      @checklist.save

      ChecklistTopic.delete_all(:checklist_id => nil)
      old_checks.each do |check|
        if check.topics.empty?
          check.destroy
        end
      end
      
      redirect_to @checklist, :notice => 'Checklist was successfully created.'

    rescue Exception => msg  
      @listdata = params[:topics_yaml]
      @checklist.errors.add(:topics,msg)

      render :action => "edit"
    end
  end

  def edit_values
    @checklist = Checklist.find params[:id]
  end
  
  def new_topic
    topic = ChecklistTopic.new
    topic.title = params[:title]

    render :partial => "topic", :layout => false, :locals => { 
      :topic => topic,
      :topic_key => params[:new_key]
    }
  end
  
  def new_check
    @checklist = Checklist.new
    check = ChecklistCheck.new
    check.check = params[:title]
    link = ChecklistTopicsCheck.new
    link.check = check

    render :partial => "check", :layout => false, :locals => { 
      :link => link,
      :link_key => params[:new_key],
      :topic_key => params[:topic_key]
    }
  end
  
  def import_check
    @checklist = Checklist.find params[:checklist_id]
    check = ChecklistCheck.find params[:check_id]
    
    link = ChecklistTopicsCheck.new
    link.check = check

    render :partial => "check", :layout => false, :locals => { 
      :link => link,
      :link_key => params[:new_key],
      :topic_key => params[:topic_key]
    }
  end

  def update_values
    @checklist = Checklist.find params[:id]
    @checklist.grade_callback = params[:checklist][:grade_callback]
    @checklist.title = params[:checklist][:title]
    @checklist.save

    existingTopics = @checklist.topics.index_by { |t| t.id.to_s }
    existingLinks = @checklist.topics_checks.includes(:check).index_by &:id

    newTopics = params[:topics] || {}
    newChecks = params[:checks] || {}

    newTopics.each do |idkey, values|
      # First we fix the scale rational values
      target = BigDecimal(values["score_target"])

      if values["scale_score"].nil?
        scale = Rational(1)
        values["score_target"] = nil
      else
        unless values["scale_denominator"].to_f == 0
          scale = Rational(values["scale_numerator"], values["scale_denominator"]).round(5)
        else
          scale = Rational(0)
        end
        values["scale_numerator"] = scale.numerator
        values["scale_denominator"] = scale.denominator
      end
      
      scoretype = Scoretype.find values[:scoretype_id]
      values.delete :scoretype_id
      values.delete :scale_score

      if values["id"] == "new"
        values.delete :id
        topic = ChecklistTopic.new values
        topic.scoretype = scoretype
        topic.checklist = @checklist
        topic.save

        existingTopics[idkey] = topic
      else 
        topic = existingTopics.fetch idkey, nil
        unless topic.nil?
          values.delete :id
          topic.scoretype = scoretype
          topic.update_attributes values
        end

      end
    end

    newChecks.each do |idkey, values|
      topic = existingTopics.fetch values["topic_id"], nil
    
      if topic.nil?
        asdf
      end

      values.delete :topic_id
      
      if values["check_id"] == "new"
        check = ChecklistCheck.new values["check"]
      else 
        check = ChecklistCheck.find values["check_id"]
        check.update_attributes values["check"]
      end

      check.save

      values.delete :check_id
      values.delete :check

      if values["id"] == "new"
        values.delete :id
        link  = ChecklistTopicsCheck.new values
        link.topic = topic
        link.check = check
        link.save

        existingTopics[idkey] = topic
      else 
        link = existingLinks.fetch idkey.to_i, nil
        unless link.nil?
          values.delete :id
          link.topic = topic
          link.check = check
          link.update_attributes values
        end
      end

    end

    params[:deleted_topics_checks] ||= []

    #Integer(,10)
    unless params[:deleted_topics].nil?
      params[:deleted_topics].each do |del_id|
        topic = @checklist.topics.find del_id rescue nil
        unless topic.nil?
          params[:deleted_topics_checks].push(*topic.topics_checks.map { |tc| tc.id })
          topic.destroy
        end
      end
    end
    
    unless params[:deleted_topics_checks].nil?
      params[:deleted_topics_checks].each do |del_id|
        link = @checklist.topics_checks.find del_id rescue nil
        
        unless link.nil?
          if link.check.topics.size > 1
            link.destroy
          else
            check = link.check
            link.destroy
            check.destroy
          end
        end

      end
    end

    redirect_to @checklist, :notice => 'Checklist was successfully updated.'
  end

  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.destroy
    redirect_to checklists_path, :notice => 'Course was destroyed'
  end

  private

  def topics_to_yaml (topics)
    StyledYAML.dump format_nice(topics.map{ |topic|
      ret = topic.attributes.reject {|key,value|
        %w(title ordering checklist_id scoretype_id).include? key or value.nil? 
      }

      if !topic.scoretype.nil?
        ret["scoretype"] = topic.scoretype.varname unless topic.scoretype.varname == "points"
      end
      ret["checks"] = topic.topics_checks.includes(:topic).map do |a|
        c = hide_ids_from :check, a.check.attributes.select {|key,val| 
          %w(id check varname feedback missing_feedback).include? key and !val.nil? and val != ""
        }
        c["value"] = a.value unless a.value == 0
        c["unchecked_value"] = a.unchecked_value unless a.unchecked_value == 0
        c
      end unless topic.checks.size == 0
      hide_ids_from :topic, ret 
    })
  end

  def yaml_to_topics(yaml)
    ordering = 1
    topics = YAML.load(yaml).map do |thash|
      thash = parse_ids_from :topic, thash
      if thash.has_key? "id"
        begin
          topic = ChecklistTopic.find thash["id"] 
          rescue
          topic = ChecklistTopic.new
        end
      else 
        topic = ChecklistTopic.new 
      end

      thash.each do |key,val|
        topic[key] = val unless %w(id topic scoretype checks ordering).include? key
      end

      topic.scoretype = Scoretype.find_by_varname thash.fetch("scoretype", "points")
      topic.title = thash["topic"]
      topic.ordering = ordering

      links = topic.topics_checks.includes(:check).index_by(&:checklist_check_id)
      ordering += 1

      check_ordering = 1
      topic.topics_checks = thash.fetch("checks", []).map do |chash|
        chash = parse_ids_from :check, chash
        if chash.has_key? "id" and not links[chash["id"]].nil?
          link = links[chash["id"]]
          check = link.check
        else 
          link = ChecklistTopicsCheck.new
          begin
            if chash.has_key? "id"
              check = ChecklistCheck.find chash["id"]
            else
              check = ChecklistCheck.new
            end
          rescue Exception => msg  
            check = ChecklistCheck.new
          end
          link.check = check
        end

        chash["feedback"] ||= ""
        chash["missing_feedback"] ||= ""
        chash.each do |key,val|
          check[key] = val unless %w(id ordering value unchecked_value).include? key
        end

        link.ordering = check_ordering
        link.value = chash["value"] || 0
        link.unchecked_value = chash["unchecked_value"] || 0
        check_ordering += 1

        if chash.has_key? "id"
          check.save 
          link.save
        end
        
        link
      end

      topic.save if thash.has_key? "id"

      topic
    end
    topics
  end

  def hide_ids_from(key,hash)
    return hash unless hash.has_key? "id"

    key = key.to_s
    id = hash["id"]
    keyval = hash[key]

    hash.delete "id"
    hash.delete key

    ret = {key+" "+id.to_s => keyval}
    hash.each { |k,v| ret[k] = v }
    ret
  end

  def parse_ids_from(idkey,hash)
    idkey = idkey.to_s
    ret = {}
    regexp = "^"+idkey+" ([0-9]+)$"

    hash.each do |key,val|
      if key.match regexp
        ret[idkey] = val
        ret["id"] = $1.to_i
      else
        ret[key] = val
      end
    end

    ret

  end

  def format_nice (coll)
    if coll.is_a? Hash
      coll.each do |key, value|
        coll[key] = format_nice(value)
      end
    elsif coll.is_a? Array
      coll = coll.map do |value|
        format_nice(value)
      end
    elsif coll.is_a? String and !coll.index("\n").nil?
      coll = StyledYAML.literal(coll)
    end
    coll
  end

end

app/helpers/checklists_helper.rb
module ChecklistsHelper

  def show_val val
    #Drop the decimal notation if it's not needed
    return 0 if val.nil?
    val = val.to_i if val.frac == 0
    val
  end

end

app/views/checklists/_check.html.erb
<% link_key = link.id unless link_key %>
<tr id="linked_check_<%= link.id %>">
  <td class="name">
    <p class="nametext">
      <%= link.check.check %>
    </p>
    <%= text_field_tag "checks[#{link_key}][check][check]", link.check.check, :class => 'check_check nosubmit' %>
    <%= hidden_field_tag "checks[#{link_key}][id]", link.id || "new", :class => 'link_id' %>
    <%= hidden_field_tag "checks[#{link_key}][ordering]", link.ordering, :class => 'check_ordering' %>
    <%= hidden_field_tag "checks[#{link_key}][check_id]", link.check.id || "new", :class => 'check_id' %>
    <%= hidden_field_tag "checks[#{link_key}][topic_id]", topic_key, :class => 'topic_id_field'  %>
  </td>
  <td class="feedbacks">
    <%= text_area_tag "checks[#{link_key}][check][feedback]", link.check.feedback, :rows => 1, :cols => 40 %>
  </td>
  <td class="feedbacks">
    <%= text_area_tag "checks[#{link_key}][check][missing_feedback]", link.check.missing_feedback, :rows => 1, :cols => 40 %>
  </td>
  <td class="values">
    <%= number_field_tag "checks[#{link_key}][value]", show_val(link.value), :step=> :any, :class => :value %>
  </td>
  <td class="values">
    <%= number_field_tag "checks[#{link_key}][unchecked_value]", show_val(link.unchecked_value), :step => :any, :class => :unchecked_value %>
  </td>
  <td>
    <button type="button" class="hoverdrop btn btn-default dropdown-toggle" data-toggle="dropdown">
      ✐
      <span class="caret"></span>
    </button>
    <div class="dropdown-menu dropdown-checkedit" role="menu">
      <div class="panel-body">
        <p>
          Variable name used in javascript code (optional)
          <%= text_field_tag "checks[#{link_key}][check][varname]", link.check.varname, :class => 'check_varname' %>
        </p>
        <% other_topics = link.check.topics.includes(:checklist).where('checklist_id != ?', @checklist.id ) %>
        <% if other_topics.size > 0 %>
          <p>This check is also linked to the following topics</p>
          <ul>
          <% other_topics.each do |t|  %>
            <li>
            <%= link_to t.title + " from "+t.checklist.title, t.checklist %>
            </li>
          <% end %>
          </ul>
          <button type="button" class="deleteCheck btn btn-danger">Remove check from this topic</button>
        
        <% else %>
          <p>This check is not present in any other topics</p>
          <button type="button" class="deleteCheck btn btn-danger">Delete this check</button>
        <% end %>
  
      </div>
    </div>
  </td>
</tr>

app/views/checklists/_grade_callback_field.html.erb
<button type="button" class="btn-link expandable collapsed" data-toggle="collapse" data-target="#grade_callback_field">
  Show grading code
</button>
<div id="grade_callback_field" class="panel panel-default collapse">
  <div class="panel-body">
    <p>Javascript code to call before final grading.</p>
    <p>You can use the variable checklist to access the checklist properties</p>
    <p>
    <%= text_area_tag "checklist[grade_callback]", checklist.grade_callback, :rows => 10, :cols => 80 %>
    </p>
  </div>
</div>

app/views/checklists/_topic.html.erb
<% topic_key = topic.id unless topic_key %>
<div class="topicContainer rounded form-group">
  <%= hidden_field_tag "topics[#{topic_key}][id]", topic.id || "new", :class => 'topic_id' %>
  <%= hidden_field_tag "topics[#{topic_key}][ordering]", topic.ordering, :class => 'topic_ordering' %>
  <div class="topic_handle">
    <%= topic.title %>
    <button type="button" class="btn-link expandable collapsed" data-toggle="collapse" data-target="#edit_topic_panel_<%= topic_key %>">
      Edit topic
    </button>
  </div>
  <div id="edit_topic_panel_<%= topic_key %>" class="panel panel-default collapse">
    <div class="panel-body">
      <div class="form-group">
        Name
        <%= text_field_tag "topics[#{topic_key}][title]", topic.title %>
      </div>
      <div class="form-group">
        Score type
        <%= collection_select("topics[#{topic_key}]", :scoretype_id, Scoretype.all, :id, :name, :selected => topic.scoretype_id) %>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <p>Javascript code to call before evaluating the score and feedback of this topic.</p>
          <%= text_area_tag "topics[#{topic_key}][init_callback]", topic.init_callback, :rows => 10, :cols => 80 %>
        </div>
        <div class="col-sm-6">
          <p>Javascript code to call after evaluating the score and feedback of this topic.</p>
          <%= text_area_tag "topics[#{topic_key}][update_callback]", topic.update_callback, :rows => 10, :cols => 80 %>
        </div>
      </div>
      <div>
        <button type="button" class="deleteTopic btn btn-danger">Delete this topic</button>
      </div>
    </div>
  </div>
  <table class="checklist_table values_table table table-striped table-condensed table-bordered" id="topic_<%= topic_key %>">
    <colgroup>
      <col span="1" style="">
      <col span="1" style="">
      <col span="1" style="">
      <col span="1" style="width: 50px;">
      <col span="1" style="width: 50px;">
    </colgroup>
    <thead>
      <tr>
        <th class="name">Check</th>
        <th class="feedbacks">Checked feedback</th>
        <th class="feedbacks">Unchecked feedback</th>
        <th class="scores">Checked</th>
        <th class="scores">Unchecked</th>
        <th>More</th>
      </tr>
    </thead>
    <tbody>
      <% topic.topics_checks.includes(:check).each do |link| %>
        <%= render partial: "check", locals: {link: link, topic_key: topic_key} %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th colspan="3" class="spanOverFeedbacks">Totals</th>
        <th>Max: <span class="max"></span></th>
        <th>Min: <span class="min"></span></th>
        <th></th>
      </tr>
      <tr>
        <th colspan="3" class="spanOverFeedbacks">

          <%= check_box_tag("topics[#{topic_key}][scale_score]", 1, !topic.score_target.nil?, :class => :scale_score) +
              label_tag("topics[#{topic_key}][scale_score]", "Scale score total to a maximum/minimum of") %>
          <%= number_field_tag "topics[#{topic_key}][score_target]", show_val(topic.score_target), :step=> :any, :class => :score_target %>
          points
          <%= hidden_field_tag "topics[#{topic_key}][scale_numerator]", topic.scale_numerator, :class => :scale_num %>
          <%= hidden_field_tag "topics[#{topic_key}][scale_denominator]", topic.scale_denominator, :class => :scale_denom %>
          <span class="pull-right">Scaled values:</span>
        </th>
        <th>Max: <span class="max_scaled"></span></th>
        <th>Min: <span class="min_scaled"></span></th>
        <th></th>
      </tr>
    </tfoot>
  </table>
  <div class="new_check_form_container">
    <p>
    <%= label_tag 'new_check_title', 'New check' %>:
    <%= text_field_tag :new_check_title, nil %>
    <button class="new_check" type="button" class="btn btn-primary">Create</button>
    <%= label_tag 'import_check', 'Import check' %>:
    <%= grouped_collection_select :import_check, nil, ChecklistTopic.includes(:checklist).order("checklists.title","checklist_topics.ordering"), :checks, :checlist_name_and_title, :id, :check, :class => "nosubmit" %>
    <button class="import_check" type="button" class="btn btn-primary">Import</button>
    </p>
  </div>
</div>

app/views/checklists/edit.html.erb
<h1>Edit checklist</h1>
<% @checklist.errors[:topics].each do |msg| %>
  <p>Error! <%= msg %></p>
<% end %>
<%= form_for(@checklist) do -%>
  <%= label_tag 'checklist[title]', 'Title' %>
  <%= text_field_tag 'checklist[title]', @checklist.title %>
  <div>
    <div style="display: inline-block; width: 60%;" >
      <%= label_tag 'topics' %>
      <br />
      <%= text_area_tag 'topics_yaml', @listdata, :size => "60x30" %>
    </div>
    <div style="display: inline-block; width: 35%;" >
      <%= label_tag 'remarks' %>
      <br />
      <%= text_area_tag 'checklist[remarks]', @checklist.remarks, :size => "60x30" %>
    </div>
  </div>

  <p>
  <%= render partial: "grade_callback_field", locals: {checklist: @checklist} %>
  </p>
  <%= hidden_field_tag 'checklist[id]', @checklist.id %>
  <%= submit_tag "Save", :class => "small-button" %>
<% end %>

app/views/checklists/edit_values.html.erb
<h2><%= @checklist.title %></h2>
<%= form_tag("/checklists/#{@checklist.id}/values/", {:id => 'checklist_'+@checklist.id.to_s}) do -%>
  <%= label_tag 'checklist[title]', 'Edit title' %>
  <%= text_field_tag 'checklist[title]', @checklist.title %>
  <%= check_box_tag(:show_feedbacks, nil, true) %>
  <%= label_tag :show_feedbacks, 'Show feedback textareas' %>
  <%= check_box_tag(:reorder_topics) %>
  <%= label_tag :reorder_topics, 'Reorder topics' %>
  <%= submit_tag "Save", :class => "small-button" %>
  <p>
  <button type="button" class="btn-link expandable collapsed" data-toggle="collapse" data-target="#grade_callback_field">
    Show grading code
  </button>
  <div id="grade_callback_field" class="panel panel-default collapse">
    <div class="panel-body">
      <p>Javascript code to call before final grading.</p>
      <p>You can use the variable checklist to access the checklist properties</p>
      <p>
      <%= text_area_tag "checklist[grade_callback]", @checklist.grade_callback, :rows => 10, :cols => 80 %>
      </p>
    </div>
  </div>
  </p>
  <p id="help">
    Drag and drop items to reorder them
    and click on check names to rename them.
  </p>
  <div class="topics" id="topics">
    <% @checklist.topics.order("ordering").each do |topic| %>
      <%= render partial: "topic", locals: {:topic => topic} %>
    <% end %>
  </div>
  <div class="rounded">
    <h2>New checklist topic</h2>
    <p>
    <%= label_tag 'new_topic_title', 'Title' %>
    <%= text_field_tag 'new_topic_title', "New topic" %>
    <button id="new_topic" type="button" class="btn btn-primary">Create</button>
    </p>
  </div>
  <%= submit_tag "Save", :class => "small-button" %>
<% end %>

app/views/checklists/index.html.erb
<h1>Checklists</h1>
<ul>
<% @checklists.each do |checklist| %>
  <li><%= link_to checklist.title, checklist %></li>
<% end %>
</ul>
<%= link_to 'New list', new_checklist_path %>

app/views/checklists/new.html.erb
<h1>Create checklist</h1>
<% @checklist.errors[:topics].each do |msg| %>
  <p>Error! <%= msg %></p>
<% end %>
<%= form_tag('/checklists') do -%>
  <%= label_tag 'checklist[title]', 'Title' %>
  <%= text_field_tag 'checklist[title]' %>
  <%= submit_tag "Save", :class => "small-button" %>
<% end %>

app/views/checklists/show.html.erb
<h1>Checklist</h1>
<div class="rounded">
  <h2><%= @checklist.title %></h2>
  <%= form_tag("/checklists/#{@checklist.id}/user/", :class => 'autograde', :id => (@registration.nil? ? "checklist" : "checklist-#{@registration.id}")) do -%>
    <% if !@registration.nil? %>
      <%= hidden_field_tag 'registration', @registration.id %>
    <% end %>
    <% @checklist.topics.order("ordering").each do |topic| %>
      <div class="topicContainer">
        <div class="topic" id="topic<%= @attribute_suffix %>_<%= topic.id %>">
          <%= topic.title %>
          <button>Done?</button>
          <span class="pull-right topicscoring">Score: <span class="scorevalue">0</span><% unless topic.score_target.nil? %>/<%= topic.score_target %></span><% end %>
        </div>
        <div class="checks">
          <% topic.checks.each do |check| %>
            <div class="check">
              <%= check_box_tag "checks[#{check.id}]", 0, check.checked?(@registration), :id => "checks#{@attribute_suffix}_#{check.id}" %>
              <%= label_tag "checks#{@attribute_suffix}_#{check.id}", " "+check.check %>
            </div>
          <% end %>
        </div>
        <div class="feedback">
        </div>
      </div>
    <% end %>
    <h2>Score</h2>
    <div class="scores">

    </div>
    <h2>Feedback</h2>

    <ul class="feedbacks">

    </ul>
  <% end %>
  <div class="remarks">
    <%= rendered(@checklist.remarks) %>
  </div>
</div>
<div class="rounded actions">
  <h2>Actions</h2>
  <%= link_to 'Edit', edit_checklist_values_path(@checklist), :class => 'small-button' %>
  <%= link_to 'Edit as YAML', edit_checklist_path(@checklist), :class => 'small-button' %>
  <%= link_to 'Delete the checklist', @checklist, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'small-button' %>
</div>
<script type="text/javascript">
  $(function() {
      $('#checklist<%= "-#{@registration.id}" unless @registration.nil? %>').autograding({
      <% @checklist.topics.order("ordering").each do |topic| %>
        "topic<%= @attribute_suffix %>_<%= topic.id %>":
        { varname: <%= raw topic.varname.to_json%>,
          scoretype: <%= raw topic.scoretype.id.to_json%>,
          scale_denominator: <%= raw topic.scale_denominator.to_json%>,
          scale_numerator: <%= raw topic.scale_numerator.to_json %>,
          update_callback: function(checklist) {
            var checks = this.checks;
            <% topic.checks.each do |check|  %>
              <% if check.has_valid_varname? %>
                var <%= check.varname %> = checks.<%= check.varname %>;
              <% end %>
            <% end %>
            <%= raw topic.update_callback %>
          },
          init_callback: function(checklist) {
            var checks = this.checks;
            <% topic.checks.each do |check|  %>
              <% if check.has_valid_varname? %>
                var <%= check.varname %> = checks.<%= check.varname %>;
              <% end %>
            <% end %>
            <%= raw topic.init_callback %>
          },
          checks: {
            <% topic.topics_checks.includes(:topic).each do |link|  %>

              "checks<%= @attribute_suffix %>_<%= link.check.id %>":
              { varname: <%= raw link.check.varname.to_json%>,
                value: <%= raw link.value.to_json%>,
                unchecked_value: <%= raw link.unchecked_value.to_json%>,
                feedback: <%= raw link.check.feedback.to_json%>,
                missing_feedback: <%= raw link.check.missing_feedback.to_json%>
              },
            <% end %>
          }
        },
      <% end %>
      "scoretypes": {
      <% @checklist.scoretypes.each do |scoretype| %>
        "<%= scoretype.id %>": 
        <%= raw scoretype.attributes.to_json %>,
      <% end %>
      },
      grade_callback: function(checklist) {
        <%= raw @checklist.grade_callback %>
      }
    });
  });
</script>