config/routes.rb
Labtool::Application.routes.draw do
  resources :peer_reviews
  resources :week_feedbacks
  resources :feedback_comments
  resources :registrations
  resources :checklists
  resources :checks
  resources :checktypes
  resources :courses
  resources :peer_reviews
  resources :users do
    post 'toggle_hidden', :on => :member
  end

  get  'checklists/:id/user/:registration_id' => 'passed_checks#show'
  post 'checklists/:id/user/' => 'passed_checks#update'
  get  'checklists/:id/values/' => 'checklists#edit_values', :as => "edit_checklist_values"
  get  'checklists/ajax/new_topic_form' => 'checklists#new_topic'
  get  'checklists/ajax/new_check_form' => 'checklists#new_check'
  get  'checklists/ajax/import_check_form' => 'checklists#import_check'
  post 'checklists/:id/values/' => 'checklists#update_values'

  post 'checktypes/:id/reorder/' => 'checks#reorder'

  match 'register(/:id)' => 'registrations#new'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  match 'courses/:id/active' => 'courses#active', :via => :post
  match 'courses/:id/inactive' => 'courses#inactive', :via => :post

  match 'week_feedbacks/note' => 'week_feedbacks#create_note', :via => :post
  match 'feedback_comments/admin_reply' => 'feedback_comments#create_admin_reply', :via => :post

  get  'mypage' => 'mypage#index'
  post 'mypage' => 'mypage#redirect'
  get  'mypage/:student_number' => 'mypage#show'
  post 'mypage/:student_number' => 'mypage#edit'
  match 'mypage/:student_number' => 'mypage#update',  :via => :put

  match 'foobar' => 'mypage#foobar'
  match 'toggle_review' => 'peer_reviews#toggle_review'
  match 'remove_review' => 'peer_reviews#remove_review'
  match 'complete_review' => 'peer_reviews#complete_review'
  match 'reset_reviews' => 'peer_reviews#reset'
  match 'generate_reviews' => 'peer_reviews#generate'
  match 'toggle_review_participation' => 'peer_reviews#toggle_participation'
  post '/peer_review' => 'peer_reviews#create'

  match 'toggle_registration' => 'registrations#toggle_activity'
  match 'toggle_demo_participation' => 'registrations#toggle_demo_participation'

  post 'users/:id/toggle_admin' => 'users#toggle_admin', :as => "user_toggle_admin"

  root :to => 'mypage#index'
end

app/models/week_feedback.rb
class WeekFeedback < ActiveRecord::Base
  attr_accessible :points, :text, :week, :hidden_text, :is_grade
  belongs_to :registration
  belongs_to :giver, class_name: 'User'
  has_many :feedback_comments

  validates :week, :numericality => {:greater_than_or_equal_to => 1}
  validates :points, :numericality => {:greater_than_or_equal_to => 0}
  validate :points_within_range

  def title
    return "Arvostelu ja kurssipalaute" if is_grade
    "viikon #{week} palaute" 
  end

  def max
    # The final grade gets a special treatment
    return 60 if is_grade
    return 3 if registration.course.nil?
    registration.course.week_feedback_max_points || 3
  end

  def user
    registration.user
  end

  def points_within_range
    errors.add(:points, "should be at most #{max}") if points.nil? or points>max
  end

end

app/controllers/week_feedbacks_controller.rb
class WeekFeedbacksController < ApplicationController

  def index
    @week_feedbacks = WeekFeedback.all
  end

  def create_note
    @registration = Registration.find(params[:registration])

    week = 1 + @registration.week_feedbacks.inject(9) { |m, w| m = w.week if w.week>m; m  }
    note = WeekFeedback.new :hidden_text => params[:hidden_text], :points => 0, :week => week

    @registration.week_feedbacks << note

    redirect_to @registration.user, :notice => 'An instructor note was created.'
  end

  def create
    params[:week_feedback]['text'] = params[:week_feedback]['text'].lstrip.rstrip
    @registration = Registration.find(params[:registration])
    earlier_feedback = @registration.feedback_for_week (params[:week_feedback][:week]).to_i

    if earlier_feedback
      @week_feedback = prepare_based_on earlier_feedback, params
      @grade = params[:grade]
      return render :action => "edit", :notice => "you already gave feedback for week #{@week_feedback.week}"
    end

    week_feedback = WeekFeedback.new(params[:week_feedback])
    week_feedback.giver = current_user
    @registration.week_feedbacks << week_feedback

    if week_feedback.valid?

      if params[:grade]
        @registration.grade = params[:grade]
        @registration.save
      end

      if params[:notify]
        student = week_feedback.user
        reviewer = current_user
        NotificationMailer.email(reviewer.email, student.email, "ks. #{mypage_url+'/'+student.student_number}", week_feedback.title, params['notify-cc'], Course.active.name).deliver
      end

      redirect_to @registration.user, :notice => 'Week feedback was successfully created.'
    else
      @week_feedback = week_feedback
      render :action => "edit"
    end

  end

  def update
    @week_feedback = WeekFeedback.find(params[:id])

    if @week_feedback.update_attributes(params[:week_feedback])
      if params[:grade]
        @week_feedback.registration.grade = params[:grade]
        @week_feedback.registration.save
      end
      redirect_to @week_feedback.registration.user, :notice => 'Week feedback was successfully updated'
    else
      @registration = Registration.find(params[:registration])
      render :action => "edit"
    end
  end

  def destroy
    @week_feedback = WeekFeedback.find(params[:id])
    @week_feedback.destroy
    redirect_to week_feedbacks_path
  end

  private

  def prepare_based_on earlier_feedback, params
    week_feedback = earlier_feedback
    week_feedback.text += "\n-------------------\n" unless params[:week_feedback][:text].empty?
    week_feedback.text += params[:week_feedback][:text] unless params[:week_feedback][:text].empty?
    week_feedback.hidden_text = "" if week_feedback.hidden_text.nil?
    week_feedback.hidden_text += "\n-------------------\n" unless week_feedback.hidden_text.empty? or params[:week_feedback][:hidden_text].empty?
    week_feedback.hidden_text += params[:week_feedback][:hidden_text] unless params[:week_feedback][:hidden_text].empty?
    week_feedback.points = params[:week_feedback][:points] unless params[:week_feedback][:points].empty?
    week_feedback.errors.add(:week, "feedback already exists!")
    week_feedback.errors.add(:text, "should perhaps be merged with the existing!")
    week_feedback.errors.add(:hidden_text, "should perhaps be merged with the existing!")
    week_feedback
  end
end

app/helpers/week_feedbacks_helper.rb
module WeekFeedbacksHelper
end

app/views/week_feedbacks/_form.html.erb
<%= form_for(@week_feedback) do |f| %>
    <% if @week_feedback.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@week_feedback.errors.count, "error") %> prohibited this week_feedback from being
            saved:</h2>

          <ul>
            <% @week_feedback.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    
    <% unless @week_feedback.is_grade %>
      <div class="field">
        Week<br/>
        <%= f.number_field :week %>
      </div>
    <% else %>
      <%= f.hidden_field :week %>
      <%= f.hidden_field :is_grade  %>
      <div class="field">
        Grade<br/>
        <%= number_field_tag :grade, @grade %>
      </div>
    <% end %>

    <div class="field">
      Points<br/>
      <%= f.number_field :points, :step => 0.5 %>
    </div>
    <div class="field">
      Text<br/>
      <%= f.text_area :text, :size => "100x10" %>
    </div>

    <div class="field">
      The instructor only text<br/>
      <%= f.text_area :hidden_text, :size => "100x10" %>
    </div>

    <%= label_tag 'notify student by email' %>
    <%= check_box_tag 'notify', true, @registration.course.email_student? %>

    <br/>
    <%= label_tag 'send the email also to you' %>
    <%= check_box_tag 'notify-cc', true, @registration.course.email_instructor? %>


    <br/>
    <br/>

    <%= hidden_field_tag 'registration', @registration.id %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/week_feedbacks/edit.html.erb
<h2>Editing week feedback for <%= link_to @registration.user, @registration.user %></h2>

<%= render 'form' %>

app/views/week_feedbacks/index.html.erb
<h1>Listing week_feedbacks</h1>

<table>
  <tr>
    <th>Points</th>
    <th>Week</th>
    <th>Text</th>
    <th></th>
  </tr>

<% @week_feedbacks.each do |week_feedback| %>
  <tr>
    <td><%= week_feedback.points %></td>
    <td><%= week_feedback.week %></td>
    <td><%= week_feedback.text %></td>
    <td><%= link_to 'Destroy', week_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Week feedback', new_week_feedback_path %>

app/views/week_feedbacks/new.html.erb
<h1>New week_feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', week_feedbacks_path %>

app/views/week_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Points:</b>
  <%= @week_feedback.points %>
</p>

<p>
  <b>Text:</b>
  <%= @week_feedback.text %>
</p>


<%= link_to 'Edit', edit_week_feedback_path(@week_feedback) %> |
<%= link_to 'Back', week_feedbacks_path %>