config/routes.rb
Labtool::Application.routes.draw do
  resources :peer_reviews
  resources :week_feedbacks
  resources :feedback_comments
  resources :registrations
  resources :checklists
  resources :checks
  resources :checktypes
  resources :courses
  resources :peer_reviews
  resources :users do
    post 'toggle_hidden', :on => :member
  end

  get  'checklists/:id/user/:registration_id' => 'passed_checks#show'
  post 'checklists/:id/user/' => 'passed_checks#update'
  get  'checklists/:id/values/' => 'checklists#edit_values', :as => "edit_checklist_values"
  get  'checklists/ajax/new_topic_form' => 'checklists#new_topic'
  get  'checklists/ajax/new_check_form' => 'checklists#new_check'
  get  'checklists/ajax/import_check_form' => 'checklists#import_check'
  post 'checklists/:id/values/' => 'checklists#update_values'

  post 'checktypes/:id/reorder/' => 'checks#reorder'

  match 'register(/:id)' => 'registrations#new'

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  resources :sessions

  match 'courses/:id/active' => 'courses#active', :via => :post
  match 'courses/:id/inactive' => 'courses#inactive', :via => :post

  match 'week_feedbacks/note' => 'week_feedbacks#create_note', :via => :post
  match 'feedback_comments/admin_reply' => 'feedback_comments#create_admin_reply', :via => :post

  get  'mypage' => 'mypage#index'
  post 'mypage' => 'mypage#redirect'
  get  'mypage/:student_number' => 'mypage#show'
  post 'mypage/:student_number' => 'mypage#edit'
  match 'mypage/:student_number' => 'mypage#update',  :via => :put

  match 'foobar' => 'mypage#foobar'
  match 'toggle_review' => 'peer_reviews#toggle_review'
  match 'remove_review' => 'peer_reviews#remove_review'
  match 'complete_review' => 'peer_reviews#complete_review'
  match 'reset_reviews' => 'peer_reviews#reset'
  match 'generate_reviews' => 'peer_reviews#generate'
  match 'toggle_review_participation' => 'peer_reviews#toggle_participation'
  post '/peer_review' => 'peer_reviews#create'

  match 'toggle_registration' => 'registrations#toggle_activity'
  match 'toggle_demo_participation' => 'registrations#toggle_demo_participation'

  post 'users/:id/toggle_admin' => 'users#toggle_admin', :as => "user_toggle_admin"

  root :to => 'mypage#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="titlebar">
  <div class="container">
      <h1>Labtool</h1>
      <nav>
      <%= link_to 'register', "/register" %>
      <%= link_to 'my page', "/mypage" %>
      |
      <% if admin? %>
        <%= link_to 'peer reviews', peer_reviews_url %>
        <%= link_to 'courses', courses_url %>
        <%= link_to 'registrations', registrations_url %>
        <%= link_to 'users', users_url %>
        <%= link_to 'checklists', checklists_url %>
      <% end %>
      <% if current_user %>
        <%= link_to "logout", logout_path %>
        <%= link_to current_user.email, user_path(current_user) %>
      <% else %>
        <%= link_to "login", login_path %>
      <% end %>
      </nav>
  </div>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>